### PR TITLE
Alfonsos branch

### PR DESCRIPTION
**Pull request by alfonsof4**
added project title and description

### CODE REVIEW

**Review by pdguerra12 — DISMISSED** [review]
User Story:

CINEMANIACS
AS A movie enthusiast,
I WANT to search movies and showtimes by zip code,
SO THAT I can go to a theatre at my desired location, to catch a movie,
WHEN I put a zip code in the search bar,
I AM GIVEN search results for movies and showtimes based on the area.

**Review by Rehtribution — APPROVED** [review]
looks good!

**Review by Rehtribution — APPROVED** [review]
good job!

**Comment by Rehtribution** [comment]
changes approved

**Review by Rehtribution — APPROVED** [review]

**Review by pdguerra12 — APPROVED** [review]

**Pull request merged**
