### PR TITLE
add image to the search result

### PR DESCRIPTION
**Pull request by richgarcia7525**

### CODE REVIEW

**Comment by richgarcia7525** [comment]
#36 add back in image poster to search result

**Comment by richgarcia7525** [comment]
copy code that was removed from 64ea36d3a66e90d14ecea824dc35da0506b17593

**Comment by Rehtribution** [comment]
conflicts and potentially old app version

**Comment by Rehtribution** [comment]
Good to go!

**Review by pdguerra12 — APPROVED** [review]

**Pull request merged**
